version: '3.6'

services: 
  postgres:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: root
      PORTGRES_PASSWORD: ecommerce
      POSTGRES_DB: ecommerce
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: 
     - "5434:5432"
    volumes: 
      - ./scripts/postgres:/docker-entrypoint-initdb.d/
      - ./datadir:/var/lib/postgresql/data
  backend:
    build: .
    ports:
      - "8080:8080"
    